name: My First Workflow
# trigger
on: 
- push

# Jobs in the workflow
jobs: 
  #job name,
  my-first-workflow:
    #OS that this workflow will be runnning on
    runs-on: ubuntu-latest

    # list od steps to perform task
    steps:
    - name: echo the date
      run: echo "The current time and date in GitHub is $(date)"
    - name: echo information about the context
      run: echo "head_ref - ${{github.head_ref }}, owner - ${{ github.repository_owner }}"
    - name: echo my secret
      run: echo "MY_SECRET is ${{ secrets.MY_SeCRET }}"